version: "3"
services:
    postgres:
        image: postgres:9.6
        ports:
            - 5432
        volumes:
            - "pgdata:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=fake_user
            - POSTGRES_PASSWORD=fake_password
            - POSTGRES_DB=events
    dev:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./data:/home/workspace/data


volumes:
    pgdata:
