data_warehouse:
  target: raw
  send_anonymous_usage_stats: false
  outputs:
    raw:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: events
      schema: raw
    development:
      type: postgres
      host: postgres
      user: airflow
      pass: airflow
      port: 5432
      dbname: events
      schema: public
      threads: 4